(function(hori){
	hori.getconfig=function(){
		return{
			"oaServerName":"mobile2.sugon.com",
			"oaMsgServer":"mobile2.sugon.com",
			"oaMobileServer":"mobile2.sugon.com",
			"serverBaseUrl":"http://192.168.1.110:90/",
			"encryptKey":"horiTech",
			"appServerHost":"http://192.168.1.110:90/",
			"appKey":"mobile"
		};
	};
})($.hori);
